### ISSUE TITLE
延迟很高

### ISSUE THREAD

**Issue by wwhai** [ar414-com/nginx-rtmp-ffmpeg-conf#1]
本地测试延迟达到了10S；
# 环境
服务器内存：32GB
带宽：100MB
CPU：E52850双路
操作系统：UbuntuServer

**Comment by jimmybytes** [comment]
如果是rtmp播放的话，延迟10秒算还好（一般延迟在2~5秒）

如果是hls(m3u8)播放的话，延迟10秒算是非常快的了（一般延迟在20-30秒）
